### ISSUE TITLE
Datasources __init__.py says to use mindsdb_native[extra_data_sources] although it has been deprecated.

### ISSUE THREAD

**Issue by ktyborowski** [mindsdb/datasources#46]
I have noticed that the information printed when a datasource is not found is referencing `mindsdb_native[extra_data_sources]`, even though it is deprecated in favour of `mindsdb`. 

eg.
https://github.com/mindsdb/datasources/blob/f9262b0ad307fde307441f6d1762450cfbb4d4c5/mindsdb_datasources/__init__.py#L19-L23
The docs [here](https://docs.mindsdb.com/features/DataSources) reference `mindsdb` .

Should this be changed? I can work on this if it needs a change.

**Comment by ZoranPandovski** [comment]
Yes, we deprecated the native repository. Please feel free to make PR with changed text

**Comment by ktyborowski** [comment]
I have noticed this in the `requirements_test.txt`. https://github.com/mindsdb/datasources/blob/d41f7c541d32af0da35b54b89611d1fbf52c8bd9/requirements_test.txt#L2

Should this be changed too?

**Comment by ZoranPandovski** [comment]
Yes, please remove that too.

**Comment by ZoranPandovski** [comment]
Yes, please remove that too.
